// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMjjeSG2QICLgJZuLdKl4G2KZ02bNxqOU',
    appId: '1:602768335672:web:4a6257bf35073feae2d7cd',
    messagingSenderId: '602768335672',
    projectId: 'project01-6ee56',
    authDomain: 'project01-6ee56.firebaseapp.com',
    storageBucket: 'project01-6ee56.firebasestorage.app',
    measurementId: 'G-ZS94ESYJSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkCfrSLxICg28SvaFnQPHv26icxy8nOpQ',
    appId: '1:602768335672:android:59a9f1dea53cb5b4e2d7cd',
    messagingSenderId: '602768335672',
    projectId: 'project01-6ee56',
    storageBucket: 'project01-6ee56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVk98cZ9rKZT4FasDITOdTXxVAZ9RLdsM',
    appId: '1:602768335672:ios:4a4426d72e40a8c7e2d7cd',
    messagingSenderId: '602768335672',
    projectId: 'project01-6ee56',
    storageBucket: 'project01-6ee56.firebasestorage.app',
    iosBundleId: 'com.example.project01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVk98cZ9rKZT4FasDITOdTXxVAZ9RLdsM',
    appId: '1:602768335672:ios:4a4426d72e40a8c7e2d7cd',
    messagingSenderId: '602768335672',
    projectId: 'project01-6ee56',
    storageBucket: 'project01-6ee56.firebasestorage.app',
    iosBundleId: 'com.example.project01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMjjeSG2QICLgJZuLdKl4G2KZ02bNxqOU',
    appId: '1:602768335672:web:a5f4c23e3fc9ae90e2d7cd',
    messagingSenderId: '602768335672',
    projectId: 'project01-6ee56',
    authDomain: 'project01-6ee56.firebaseapp.com',
    storageBucket: 'project01-6ee56.firebasestorage.app',
    measurementId: 'G-F7XXTZFJT8',
  );
}
